FROM node:20 AS builder

WORKDIR /app
COPY frontend/ ./
RUN npm install --force
RUN npm run build

FROM node:20 AS tester

WORKDIR /app
COPY frontend/ ./
RUN npm install --force
RUN npm test

FROM nginx:alpine

RUN apk add --no-cache gettext

COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/frontend/entrypoint.sh /entrypoint.sh
COPY docker/frontend/nginx.conf.template /etc/nginx/conf.d/default.conf.template

RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]